[project]
name = "photonyx-engine"
version = "0.1.0"
description = "Core processes for interacting with AsyncSiril"
readme = "README.md"
authors = [
    { name = "Kyle LeNeau" }
]
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=24.1.0",
    "astropy>=7.1.0",
    "async-siril>=0.2.0",
    "asyncio>=4.0.0",
    "photonyx-common",
    "structlog>=25.4.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
photonyx-common = { workspace = true }
