[project]
name = "photonyx-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kyle LeNeau" }
]
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=24.1.0",
    "astropy>=7.1.0",
    "async-siril>=0.3.0",
    "asyncio>=3.4.3",
    "cappa>=0.29.0",
    "orjson>=3.11.2",
    "photonyx-cli",
    "photonyx-engine",
    "pydantic>=2.11.7",
    "pydantic-yaml>=1.6.0",
    "pydash>=8.0.5",
    "structlog>=25.4.0",
]

[project.scripts]
photonyx-cli = "photonyx_cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
photonyx-engine = { workspace = true }
