xflags::xflags! {
    src "./src/flags.rs"

    /// Run custom build command.
    cmd xtask {

        /// Run cargo test and cargo clippy before merge
        cmd check {
            /// Format the code first
            optional --fmt
        }

        /// Export all siril commands that are scriptable
        cmd export-siril-commands {
            /// Clean download and generated
            optional --clean
        }

        /// Merge generated siril commands with implementations and report delta
        cmd merge-siril-commands {
            // How the missing implementations
            optional --show-missing
        }
    }
}

// generated start
// The following code is generated by `xflags` macro.
// Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
#[derive(Debug)]
pub struct Xtask {
    pub subcommand: XtaskCmd,
}

#[derive(Debug)]
pub enum XtaskCmd {
    Check(Check),
    ExportSirilCommands(ExportSirilCommands),
    MergeSirilCommands(MergeSirilCommands),
}

#[derive(Debug)]
pub struct Check {
    pub fmt: bool,
}

#[derive(Debug)]
pub struct ExportSirilCommands {
    pub clean: bool,
}

#[derive(Debug)]
pub struct MergeSirilCommands {
    pub show_missing: bool,
}

impl Xtask {
    #[allow(dead_code)]
    pub fn from_env_or_exit() -> Self {
        Self::from_env_or_exit_()
    }

    #[allow(dead_code)]
    pub fn from_env() -> xflags::Result<Self> {
        Self::from_env_()
    }

    #[allow(dead_code)]
    pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
        Self::from_vec_(args)
    }
}
// generated end
